### ISSUE TITLE
After authorizing site via github. Redirects to / landing page

### ISSUE THREAD

**Issue by nicomen** [mojoconf/MCT#50] opened 2015-03-24 14:00 UTC
It should redirect to the page you came from so you can continue the registration. Also it should keep the ticket type you selected open.

**Comment by jhthorsen** [comment] 2015-04-02 20:25
I'm not sure if this is suddenly fixed, but I cannot reproduce. Will close it. Please reopen if you have further information @nicomen.

**Closed as completed by jhthorsen** 2015-04-02 20:25 UTC
Labels: wontfix
